version: '2'
volumes:
  db-data: {}
services:
  konga:
    image: pantsel/konga
    environment:
      NODE_ENV: production
    stdin_open: true
    network_mode: bridge
    volumes:
    - /var/data/konga:/app/kongadata
    tty: true
    links:
    - kong:kong
    ports:
    - 1337:1337/tcp
    labels:
      io.rancher.container.pull_image: always
  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
    network_mode: bridge
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - 5432:5432/tcp
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
    links:
    - postgres:kong-database
    ports:
    - 8000:8000/tcp
    - 443:8443/tcp
    - 8001:8001/tcp
    - 7946:7946/tcp
    - 7946:7946/udp